import { BookArray } from "./Types.ts";

const NETBibleBooks: BookArray = [
    {
        division: "FT",
        name: "Genesis",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 67, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 55, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 37, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 38, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 39, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 40, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 41, verses: { first: 1, last: 57, gaps: [] } },
            { chapter: 42, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 43, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 44, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 45, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 46, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 47, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 48, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 49, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 50, verses: { first: 1, last: 26, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Exodus",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 51, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 37, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 38, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 39, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 40, verses: { first: 1, last: 38, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Leviticus",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 47, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 59, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 57, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 44, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 55, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 34, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Numbers",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 54, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 51, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 49, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 89, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 45, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 41, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 50, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 41, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 65, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 54, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 42, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 56, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 13, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Deuteronomy",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 49, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 68, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 52, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 12, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Joshua",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 63, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 51, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 45, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 33, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Judges",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 57, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 48, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 25, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Ruth",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 22, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "1 Samuel",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 52, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 58, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 42, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 44, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 13, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "2 Samuel",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 51, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 25, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "1 Kings",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 53, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 51, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 66, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 53, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "2 Kings",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 44, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 41, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 30, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "1 Chronicles",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 54, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 55, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 81, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 44, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 47, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 30, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "2 Chronicles",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 42, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 23, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Ezra",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 70, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 44, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Nehemiah",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 73, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 47, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 31, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Esther",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 3, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Job",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 37, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 38, verses: { first: 1, last: 41, gaps: [] } },
            { chapter: 39, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 40, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 41, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 42, verses: { first: 1, last: 17, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Psalms",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 50, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 37, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 38, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 39, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 40, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 41, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 42, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 43, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 44, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 45, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 46, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 47, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 48, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 49, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 50, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 51, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 52, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 53, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 54, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 55, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 56, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 57, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 58, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 59, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 60, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 61, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 62, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 63, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 64, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 65, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 66, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 67, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 68, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 69, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 70, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 71, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 72, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 73, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 74, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 75, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 76, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 77, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 78, verses: { first: 1, last: 72, gaps: [] } },
            { chapter: 79, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 80, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 81, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 82, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 83, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 84, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 85, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 86, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 87, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 88, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 89, verses: { first: 1, last: 52, gaps: [] } },
            { chapter: 90, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 91, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 92, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 93, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 94, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 95, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 96, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 97, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 98, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 99, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 100, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 101, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 102, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 103, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 104, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 105, verses: { first: 1, last: 45, gaps: [] } },
            { chapter: 106, verses: { first: 1, last: 48, gaps: [] } },
            { chapter: 107, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 108, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 109, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 110, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 111, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 112, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 113, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 114, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 115, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 116, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 117, verses: { first: 1, last: 2, gaps: [] } },
            { chapter: 118, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 119, verses: { first: 1, last: 176, gaps: [] } },
            { chapter: 120, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 121, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 122, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 123, verses: { first: 1, last: 4, gaps: [] } },
            { chapter: 124, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 125, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 126, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 127, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 128, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 129, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 130, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 131, verses: { first: 1, last: 3, gaps: [] } },
            { chapter: 132, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 133, verses: { first: 1, last: 3, gaps: [] } },
            { chapter: 134, verses: { first: 1, last: 3, gaps: [] } },
            { chapter: 135, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 136, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 137, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 138, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 139, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 140, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 141, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 142, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 143, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 144, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 145, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 146, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 147, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 148, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 149, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 150, verses: { first: 1, last: 6, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Proverbs",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 31, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Ecclesiastes",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 14, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "The Song of Songs",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 14, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Isaiah",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 6, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 37, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 38, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 39, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 40, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 41, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 42, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 43, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 44, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 45, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 46, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 47, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 48, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 49, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 50, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 51, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 52, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 53, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 54, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 55, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 56, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 57, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 58, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 59, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 60, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 61, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 62, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 63, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 64, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 65, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 66, verses: { first: 1, last: 24, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Jeremiah",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 44, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 37, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 38, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 39, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 40, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 41, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 42, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 43, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 44, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 45, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 46, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 47, verses: { first: 1, last: 7, gaps: [] } },
            { chapter: 48, verses: { first: 1, last: 47, gaps: [] } },
            { chapter: 49, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 50, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 51, verses: { first: 1, last: 64, gaps: [] } },
            { chapter: 52, verses: { first: 1, last: 34, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Lamentations",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 66, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 22, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Ezekiel",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 63, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 49, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 49, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 29, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 30, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 31, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 32, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 33, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 34, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 35, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 36, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 37, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 38, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 39, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 40, verses: { first: 1, last: 49, gaps: [] } },
            { chapter: 41, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 42, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 43, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 44, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 45, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 46, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 47, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 48, verses: { first: 1, last: 35, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Daniel",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 49, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 45, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 13, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Hosea",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 5, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 9, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Joel",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 21, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Amos",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 15, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Obadiah",
        chapters: [{ chapter: 1, verses: { first: 1, last: 21, gaps: [] } }],
    },
    {
        division: "FT",
        name: "Jonah",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 11, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Micah",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 20, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Nahum",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 19, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Habakkuk",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 19, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Zephaniah",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 20, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Haggai",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 23, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Zechariah",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 9, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 21, gaps: [] } },
        ],
    },
    {
        division: "FT",
        name: "Malachi",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 6, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Matthew",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 48, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 42, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 50, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 58, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 27, gaps: [21] } },
            { chapter: 18, verses: { first: 1, last: 35, gaps: [11] } },
            { chapter: 19, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 39, gaps: [14] } },
            { chapter: 24, verses: { first: 1, last: 51, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 46, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 75, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 66, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 20, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Mark",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 45, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 41, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 56, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 37, gaps: [16] } },
            { chapter: 8, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 50, gaps: [44, 46] } },
            { chapter: 10, verses: { first: 1, last: 52, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 33, gaps: [26] } },
            { chapter: 12, verses: { first: 1, last: 44, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 72, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 47, gaps: [28] } },
            { chapter: 16, verses: { first: 1, last: 20, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Luke",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 80, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 52, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 44, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 49, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 50, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 56, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 62, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 42, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 54, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 59, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 37, gaps: [36] } },
            { chapter: 18, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 48, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 47, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 71, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 56, gaps: [17] } },
            { chapter: 24, verses: { first: 1, last: 53, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "John",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 51, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 54, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 47, gaps: [4] } },
            { chapter: 6, verses: { first: 1, last: 71, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 53, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 59, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 41, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 42, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 57, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 50, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 42, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 25, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Acts",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 47, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 37, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 42, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 60, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 40, gaps: [37] } },
            { chapter: 9, verses: { first: 1, last: 43, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 48, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 52, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 41, gaps: [34] } },
            { chapter: 16, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 41, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 38, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 23, verses: { first: 1, last: 35, gaps: [] } },
            { chapter: 24, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 25, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 26, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 27, verses: { first: 1, last: 44, gaps: [] } },
            { chapter: 28, verses: { first: 1, last: 31, gaps: [29] } },
        ],
    },
    {
        division: "NT",
        name: "Romans",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 36, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 27, gaps: [24] } },
        ],
    },
    {
        division: "NT",
        name: "1 Corinthians",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 34, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 58, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 24, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "2 Corinthians",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 13, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Galatians",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 31, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 18, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Ephesians",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 32, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 33, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 24, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Philippians",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 30, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 23, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Colossians",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 23, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 18, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "1 Thessalonians",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 28, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "2 Thessalonians",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 12, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 18, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "1 Timothy",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 21, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "2 Timothy",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 22, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Titus",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 15, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "Philemon",
        chapters: [{ chapter: 1, verses: { first: 1, last: 25, gaps: [] } }],
    },
    {
        division: "NT",
        name: "Hebrews",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 16, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 28, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 39, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 40, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 25, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "James",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 26, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 20, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "1 Peter",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 25, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 14, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "2 Peter",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 18, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "1 John",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 10, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 21, gaps: [] } },
        ],
    },
    {
        division: "NT",
        name: "2 John",
        chapters: [{ chapter: 1, verses: { first: 1, last: 13, gaps: [] } }],
    },
    {
        division: "NT",
        name: "3 John",
        chapters: [{ chapter: 1, verses: { first: 1, last: 14, gaps: [] } }],
    },
    {
        division: "NT",
        name: "Jude",
        chapters: [{ chapter: 1, verses: { first: 1, last: 25, gaps: [] } }],
    },
    {
        division: "NT",
        name: "Revelation",
        chapters: [
            { chapter: 1, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 2, verses: { first: 1, last: 29, gaps: [] } },
            { chapter: 3, verses: { first: 1, last: 22, gaps: [] } },
            { chapter: 4, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 5, verses: { first: 1, last: 14, gaps: [] } },
            { chapter: 6, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 7, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 8, verses: { first: 1, last: 13, gaps: [] } },
            { chapter: 9, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 10, verses: { first: 1, last: 11, gaps: [] } },
            { chapter: 11, verses: { first: 1, last: 19, gaps: [] } },
            { chapter: 12, verses: { first: 1, last: 17, gaps: [] } },
            { chapter: 13, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 14, verses: { first: 1, last: 20, gaps: [] } },
            { chapter: 15, verses: { first: 1, last: 8, gaps: [] } },
            { chapter: 16, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 17, verses: { first: 1, last: 18, gaps: [] } },
            { chapter: 18, verses: { first: 1, last: 24, gaps: [] } },
            { chapter: 19, verses: { first: 1, last: 21, gaps: [] } },
            { chapter: 20, verses: { first: 1, last: 15, gaps: [] } },
            { chapter: 21, verses: { first: 1, last: 27, gaps: [] } },
            { chapter: 22, verses: { first: 1, last: 21, gaps: [] } },
        ],
    },
];

export default NETBibleBooks;
